name: 'Dependabot Helper'
description: 'Auto approve and auto merge Dependabot pull requests'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
